import type { Product } from '@/types';

/* ─────────────────────────────────────────────────────────────────────────────
   Static seed data — used as fallback when Supabase is not configured.
   Matches the supabase/schema.sql seed exactly.
───────────────────────────────────────────────────────────────────────────── */
export const PRODUCTS: Product[] = [
  // ── CORPS / BODY ────────────────────────────────────────────────────────
  {
    id: '1', product_code: 'MKB-0001',
    slug: 'mkb0001-almond-glow-body-lotion',
    name_fr: 'Almond Glow — Lotion Clarifiante Corps',
    name_en: 'Almond Glow — Clarifying Body Lotion',
    description_fr: 'Lotion corps éclaircissante enrichie en Vitamine C pour une peau lumineuse et unifiée. Formule légère à absorption rapide.',
    description_en: 'Brightening body lotion enriched with Vitamin C for a radiant and even complexion. Lightweight, fast-absorbing formula.',
    category: 'body', price_usd: 18,
    images: ['/images/products/almond-glow-single.png', '/images/products/almond-glow-korea-glow.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '2', product_code: 'MKB-0002',
    slug: 'mkb0002-korea-glow-skin-gel-wash',
    name_fr: 'Korea Glow Skin — Gel Nettoyant Blanchissant',
    name_en: 'Korea Glow Skin — Whitening Body Gel Wash',
    description_fr: 'Gel douche corps blanchissant et purifiant à la formule coréenne. Laisse la peau douce, claire et fraîche.',
    description_en: 'Korean-formula whitening and purifying body gel wash. Leaves skin soft, clear and refreshed.',
    category: 'body', price_usd: 20,
    images: ['/images/products/almond-glow-korea-glow.png', '/images/products/almond-glow-korea-glow-2.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '3', product_code: 'MKB-0003',
    slug: 'mkb0003-vitamin-c-body-lotion-3days',
    name_fr: 'Lotion Corps Vitamine C 3 Jours (Lovska)',
    name_en: 'Vitamin C Body Lotion 3 Days (Lovska)',
    description_fr: 'Duo lotion + sérum Vitamine C. Résultats visibles en seulement 3 jours. Peau lumineuse garantie.',
    description_en: 'Vitamin C lotion + serum duo. Visible results in just 3 days. Guaranteed glowing skin.',
    category: 'body', price_usd: 15,
    images: ['/images/products/vitamin-c-body-lotion-3days.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '4', product_code: 'MKB-0004',
    slug: 'mkb0004-aha-body-lotion-3days',
    name_fr: 'Lotion Corps AHA 3 Jours (Lovska)',
    name_en: 'AHA Body Lotion 3 Days (Lovska)',
    description_fr: 'Lotion corps aux acides AHA. Exfolie en douceur pour une peau plus douce et lumineuse dès 3 jours.',
    description_en: 'AHA body lotion. Gently exfoliates for softer, more radiant skin from day 3.',
    category: 'body', price_usd: 15,
    images: ['/images/products/aha-body-lotion-3days.png'],
    stock_status: 'in_stock', is_active: true, is_featured: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '5', product_code: 'MKB-0005',
    slug: 'mkb0005-thai-whitening-body-cream',
    name_fr: 'Thai Whitening Body Cream 500g',
    name_en: 'Thai Whitening Body Cream 500g',
    description_fr: 'Crème corps blanchissante format 500g. Hydrate, illumine et unifie le teint en profondeur.',
    description_en: '500g whitening body cream. Deeply hydrates, brightens and evens skin tone.',
    category: 'body', price_usd: 22,
    images: ['/images/products/thai-whitening-body-cream.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '6', product_code: 'MKB-0006',
    slug: 'mkb0006-fonce-body-lotion',
    name_fr: 'Fonce Body Lotion',
    name_en: 'Fonce Body Lotion',
    description_fr: 'Lotion corps nourrissante pour une peau souple et hydratée. Parfum délicat et texture légère.',
    description_en: 'Nourishing body lotion for supple and hydrated skin. Delicate fragrance and light texture.',
    category: 'body', price_usd: 16,
    images: ['/images/products/almond-glow-korea-glow-2.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '7', product_code: 'MKB-0007',
    slug: 'mkb0007-glycolic-acid-body-lotion',
    name_fr: 'Lotion Corps Acide Glycolique',
    name_en: 'Glycolic Acid Body Lotion',
    description_fr: 'Lotion corps professionnelle à l\'acide glycolique. Exfolie, lisse et uniformise la peau.',
    description_en: 'Professional glycolic acid body lotion. Exfoliates, smooths and evens skin.',
    category: 'body', price_usd: 19,
    images: ['/images/products/glycolic-acid-body-lotion.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '8', product_code: 'MKB-0008',
    slug: 'mkb0008-cindella-vitamin-c-100',
    name_fr: 'Cindella Vitamine C 100%',
    name_en: 'Cindella Vitamin C 100%',
    description_fr: 'Grand flacon de lotion Vitamine C 100% pure. Action éclaircissante et anti-taches puissante.',
    description_en: 'Large bottle of 100% pure Vitamin C lotion. Powerful brightening and anti-dark spot action.',
    category: 'body', price_usd: 24,
    images: ['/images/products/banners/cindella-vitamin-c-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '9', product_code: 'MKB-0009',
    slug: 'mkb0009-makari-naturalle-body-cream',
    name_fr: 'Makari Naturalle Crème Corps',
    name_en: 'Makari Naturalle Body Cream',
    description_fr: 'Crème corps Makari Naturalle aux extraits naturels. Nourrit et illumine la peau.',
    description_en: 'Makari Naturalle body cream with natural extracts. Nourishes and brightens skin.',
    category: 'body', price_usd: 20,
    images: ['/images/products/banners/makari-naturalle-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  // ── VISAGE / FACE ────────────────────────────────────────────────────────
  {
    id: '10', product_code: 'MKB-0010',
    slug: 'mkb0010-biovene-eclat-supreme',
    name_fr: 'Biovène Éclat Suprême',
    name_en: 'Biovène Éclat Suprême',
    description_fr: 'L\'apogée du luxe en soin de la peau. Pot violet et or. Hydratation intense, éclat extraordinaire.',
    description_en: 'The pinnacle of luxury skincare. Violet and gold pot. Intense hydration, extraordinary radiance.',
    category: 'face', price_usd: 35,
    images: ['/images/products/banners/biovene-eclat-supreme-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '11', product_code: 'MKB-0011',
    slug: 'mkb0011-biovene-concentre-de-luxe',
    name_fr: 'Biovène Concentré de Luxe (Sérum)',
    name_en: 'Biovène Concentré de Luxe (Serum)',
    description_fr: 'Sérum visage haut de gamme en flacon vertical élégant. Concentré d\'actifs pour une peau parfaite.',
    description_en: 'Premium face serum in elegant vertical bottle. Concentrated actives for perfect skin.',
    category: 'face', price_usd: 28,
    images: ['/images/products/banners/biovene-concentre-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '12', product_code: 'MKB-0012',
    slug: 'mkb0012-kojic-glow-skin-complete-set',
    name_fr: 'Kojic Glow Skin — Set Complet',
    name_en: 'Kojic Glow Skin — Complete Set',
    description_fr: 'Set complet Kojic : lotion, savon, crème et sérum. Solution tout-en-un pour une peau éclatante.',
    description_en: 'Complete Kojic set: lotion, soap, cream and serum. All-in-one solution for radiant skin.',
    category: 'face', price_usd: 45,
    images: ['/images/products/kojic-glow-skin-set.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '13', product_code: 'MKB-0013',
    slug: 'mkb0013-bride-cream',
    name_fr: 'Bride Cream — Crème Mariées',
    name_en: 'Bride Cream — Bridal Cream',
    description_fr: 'Crème spécialement formulée pour les mariées. Peau parfaitement lisse et lumineuse pour votre grand jour.',
    description_en: 'Specially formulated cream for brides. Perfectly smooth and radiant skin for your big day.',
    category: 'face', price_usd: 25,
    images: ['/images/products/banners/bride-cream-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '14', product_code: 'MKB-0014',
    slug: 'mkb0014-dreamwhite-beauty-cream',
    name_fr: 'DreamWhite Beauty Cream',
    name_en: 'DreamWhite Beauty Cream',
    description_fr: 'Crème beauté DreamWhite pour un teint clarifié et unifié. Texture onctueuse à absorption rapide.',
    description_en: 'DreamWhite beauty cream for a clarified and even complexion. Fast-absorbing creamy texture.',
    category: 'face', price_usd: 18,
    images: ['/images/products/banners/dreamwhite-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '15', product_code: 'MKB-0015',
    slug: 'mkb0015-anti-acne-complete-set',
    name_fr: 'Anti-Acné — Set Complet',
    name_en: 'Anti-Acne — Complete Set',
    description_fr: 'Coffret complet anti-acné. Traitement multi-étapes pour une peau nette et purifiée.',
    description_en: 'Complete anti-acne kit. Multi-step treatment for clear and purified skin.',
    category: 'face', price_usd: 40,
    images: ['/images/ceo/ceo-anti-acne-set.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  // ── EXFOLIANT ────────────────────────────────────────────────────────────
  {
    id: '16', product_code: 'MKB-0016',
    slug: 'mkb0016-extra-strong-whitening-molato-scrub',
    name_fr: 'Extra Strong Whitening Molato Scrub',
    name_en: 'Extra Strong Whitening Molato Scrub',
    description_fr: 'Gommage corps blanchissant extra-fort. Texture orange vif pour une exfoliation intense.',
    description_en: 'Extra-strong whitening body scrub. Vibrant orange texture for intense exfoliation.',
    category: 'body', price_usd: 20,
    images: ['/images/products/extra-strong-molato-scrub.png'],
    stock_status: 'in_stock', is_active: true, is_featured: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  // ── PARFUMS / FRAGRANCES ─────────────────────────────────────────────────
  {
    id: '17', product_code: 'MKB-0017',
    slug: 'mkb0017-malkia-intense-parfum',
    name_fr: 'Malkia Intense — Parfum',
    name_en: 'Malkia Intense — Perfume',
    description_fr: 'Le parfum signature de la marque. Une fragrance intense et envoûtante qui fait votre journée fraîche.',
    description_en: 'The brand\'s signature fragrance. An intense and captivating scent that makes your day fresh.',
    category: 'fragrance', price_usd: 30,
    images: ['/images/ceo/ceo-malkia-intense.png'],
    stock_status: 'in_stock', is_active: true, is_featured: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '18', product_code: 'MKB-0018',
    slug: 'mkb0018-la-tchadienne-parfum',
    name_fr: 'La Tchadienne — Parfum de Niche',
    name_en: 'La Tchadienne — Niche Perfume',
    description_fr: 'Parfum de niche aux notes africaines envoûtantes. Un hommage à l\'élégance africaine.',
    description_en: 'Niche perfume with captivating African notes. A tribute to African elegance.',
    category: 'fragrance', price_usd: 28,
    images: ['/images/ceo/ceo-la-tchadienne.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '19', product_code: 'MKB-0019',
    slug: 'mkb0019-white-premium-parfum',
    name_fr: 'Parfum Blanc Premium',
    name_en: 'White Premium Parfum',
    description_fr: 'Flacon classique de parfum blanc premium. Fragrance fraîche et sophistiquée.',
    description_en: 'Classic white premium perfume bottle. Fresh and sophisticated fragrance.',
    category: 'fragrance', price_usd: 25,
    images: ['/images/products/banners/white-parfum-shop.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
  // ── BIEN-ÊTRE / WELLNESS ─────────────────────────────────────────────────
  {
    id: '20', product_code: 'MKB-0020',
    slug: 'mkb0020-flat-tummy-tea-28-sachets',
    name_fr: 'Flat Tummy Tea (28 sachets)',
    name_en: 'Flat Tummy Tea (28 sachets)',
    description_fr: 'Thé minceur en 28 sachets pour un ventre plat. Formule naturelle pour drainer et purifier.',
    description_en: '28-sachet slimming tea for a flat tummy. Natural formula to drain and purify the body.',
    category: 'wellness', price_usd: 15,
    images: ['/images/models/avatar-flat-tummy-tea.png'],
    stock_status: 'in_stock', is_active: true, is_featured: false,
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.is_featured);

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.category === product.category && p.id !== product.id
  ).slice(0, limit);
}
